import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class', '[data-theme="dark"]'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Algorythm primary palette
        'celje': 'var(--celje-yellow)',
        'celje-bright': 'var(--celje-yellow-soft)',
        'celje-dim': 'var(--celje-yellow-2)',
        'ink-0': 'var(--ink-0)',
        'ink-1': 'var(--ink-1)',
        'ink-2': 'var(--ink-2)',
        'ink-3': 'var(--ink-3)',
        'ink-4': 'var(--ink-4)',
        'bg-0': 'var(--bg-0)',
        'bg-1': 'var(--bg-1)',
        'bg-2': 'var(--bg-2)',
        'bg-3': 'var(--bg-3)',
        'bg-4': 'var(--bg-4)',
        'line': 'var(--line)',
        'line-2': 'var(--line-2)',
        'good': 'var(--good)',
        'warn': 'var(--warn)',
        'bad': 'var(--bad)',
        'info': 'var(--info)',

        // Legacy semantic aliases — preserved so existing markup keeps working
        'void': 'var(--bg)',
        'surface-0': 'var(--bg)',
        'surface-1': 'var(--surface-1)',
        'surface-2': 'var(--surface-2)',
        'surface-3': 'var(--surface-3)',
        'surface-4': 'var(--surface-4)',
        'surface-5': 'var(--surface-5)',
        'border-subtle': 'var(--border)',
        'border-dim': 'var(--border-dim)',
        'border-bright': 'var(--border-bright)',
        'text-primary': 'var(--text)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        'text-dim': 'var(--text-dim)',
        'accent': 'var(--accent)',
        'accent-bright': 'var(--accent-bright)',
        'accent-dim': 'var(--accent-dim)',
        'accent-glow': 'var(--accent-glow)',
        'cyan': 'var(--cyan)',
        'cyan-bright': 'var(--cyan-bright)',
        'cyan-dim': 'var(--cyan-dim)',
        'gold': 'var(--gold)',
        'gold-bright': 'var(--gold-bright)',
        'gold-dim': 'var(--gold-dim)',
        'score-elite': 'var(--score-elite)',
        'score-good': 'var(--score-good)',
        'score-mid': 'var(--score-mid)',
        'score-low': 'var(--score-low)',
        'score-poor': 'var(--score-poor)',
        'chem-strong': 'var(--score-elite)',
        'chem-medium': 'var(--score-mid)',
        'chem-weak': 'var(--score-poor)',
        'pitch-bg': 'var(--pitch-bg)',
        'pitch-bright': 'var(--pitch-bright)',
        'pitch-line': 'var(--pitch-line)',
      },
      fontFamily: {
        display: ['var(--font-display)', 'sans-serif'],
        body: ['var(--font-body)', 'sans-serif'],
        sans: ['var(--font-sans)', 'sans-serif'],
        mono: ['var(--font-mono)', 'monospace'],
      },
      boxShadow: {
        'card': '0 4px 24px rgba(0,0,0,0.4), inset 0 1px 0 rgba(255,255,255,0.05)',
        'card-hover': '0 8px 40px rgba(0,0,0,0.5), inset 0 1px 0 rgba(255,255,255,0.08)',
        'glow-accent': '0 0 20px var(--accent-glow)',
        'glow-gold': '0 0 20px var(--gold-glow)',
        'glow-green': '0 0 20px rgba(91, 211, 146, 0.4)',
        'player-card': '0 8px 32px rgba(0,0,0,0.6), 0 0 0 1px rgba(255,255,255,0.05)',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'slide-in-right': 'slideInRight 0.3s ease-out',
        'slide-up': 'slideUp 0.25s ease-out',
        'fade-in': 'fadeIn 0.2s ease-out',
      },
      keyframes: {
        slideInRight: {
          '0%': { transform: 'translateX(20px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
      borderRadius: {
        'card': '12px',
        'panel': '16px',
        'modal': '20px',
      },
    },
  },
  plugins: [],
};

export default config;
